[package]
name = "hanoi-gif-renderer"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A CLI tool that generates an ASCII GIF of the Tower of Hanoi solving process"
license = "MIT"

[dependencies]
image = "0.24.6"
gif = "0.12.0"
